blank_issues_enabled: false
contact_links:
  - name: â­ï¸ Allure Report | main repository | give us a â­ï¸
    url: https://github.com/allure-framework/allure2
    about: For Allure Report related issues. If you not sure what 
  - name: ğŸ’¬ Allure Report Community - for bugs, issues, dedicated support and more!
    url: https://github.com/orgs/allure-framework/discussions
    about: Please ask and answer questions here.
  - name: ğŸ’š Allure TestOps Support
    url: https://help.qameta.io/support/home
    about: Please report Allure TestOps issues here.
